import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { requireAdminAuth } from '@/lib/requireAuth'
type Context = { params: Promise<{ id: string }> }
function unauthorizedResponse() { return NextResponse.json({ error: 'No autorizado' }, { status: 401 }) }
function storagePath(url: unknown) { const marker = '/storage/v1/object/public/portfolio-media/'; return typeof url === 'string' && url.includes(marker) ? decodeURIComponent(url.split(marker)[1]) : null }

export async function POST(request: Request, { params }: Context) { try { await requireAdminAuth() } catch { return unauthorizedResponse() }; try { const { id } = await params; const body = await request.json(); const url = typeof body.url === 'string' ? body.url.trim() : ''; const tipo = body.tipo === 'video' ? 'video' : 'imagen'; const thumbnail_url = typeof body.thumbnail_url === 'string' && body.thumbnail_url.trim() ? body.thumbnail_url.trim() : null; if (!url) return NextResponse.json({ error: 'URL requerida' }, { status: 400 }); const client = createAdminClient(); const { count, error: countError } = await client.from('proyecto_media').select('id', { count: 'exact', head: true }).eq('proyecto_id', id); if (countError) return NextResponse.json({ error: countError.message }, { status: 500 }); if ((count ?? 0) >= 10) return NextResponse.json({ error: 'Máximo 10 archivos por proyecto' }, { status: 400 }); const { data: last } = await client.from('proyecto_media').select('orden').eq('proyecto_id', id).order('orden', { ascending: false }).limit(1).maybeSingle(); const { data, error } = await client.from('proyecto_media').insert({ proyecto_id: id, url, tipo, thumbnail_url, orden: last ? last.orden + 1 : 0 }).select().single(); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json(data, { status: 200 }) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Error desconocido' }, { status: 500 }) } }
export async function DELETE(request: Request, { params }: Context) { try { await requireAdminAuth() } catch { return unauthorizedResponse() }; const { id } = await params; const mediaId = new URL(request.url).searchParams.get('mediaId'); if (!mediaId) return NextResponse.json({ error: 'MediaId requerido' }, { status: 400 }); const client = createAdminClient(); const { data: all, error: listError } = await client.from('proyecto_media').select('id, url, thumbnail_url').eq('proyecto_id', id); if (listError) return NextResponse.json({ error: listError.message }, { status: 500 }); const item = (all ?? []).find((entry) => entry.id === mediaId); if (!item) return NextResponse.json({ error: 'Archivo no encontrado' }, { status: 404 }); if ((all ?? []).length <= 1) return NextResponse.json({ error: 'El proyecto debe tener al menos 1 imagen o video' }, { status: 400 }); for (const url of [item.url, item.thumbnail_url]) { const path = storagePath(url); if (path) { console.log('Eliminando media de proyecto de Storage:', path); const { error } = await client.storage.from('portfolio-media').remove([path]); if (error) console.error('No se pudo eliminar la media de proyecto:', error) } } const { error } = await client.from('proyecto_media').delete().eq('id', mediaId).eq('proyecto_id', id); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ success: true }, { status: 200 }) }

export async function PUT(request: Request, { params }: Context) { try { await requireAdminAuth() } catch { return unauthorizedResponse() }; const { id } = await params; const body = await request.json(); if (!Array.isArray(body)) return NextResponse.json({ error: 'Se esperaba un array de IDs' }, { status: 400 }); const client = createAdminClient(); for (const [index, mediaId] of body.entries()) { const { error } = await client.from('proyecto_media').update({ orden: index }).eq('id', mediaId).eq('proyecto_id', id); if (error) return NextResponse.json({ error: error.message }, { status: 500 }) } return NextResponse.json({ success: true }, { status: 200 }) }
