'use client'

import { useEffect, useRef, useState } from 'react'
import { DndContext, closestCenter } from '@dnd-kit/core'
import { rectSortingStrategy, SortableContext } from '@dnd-kit/sortable'
import { Loader2, Pencil, Trash2, Video } from 'lucide-react'
import { generateVideoThumbnail } from '@/lib/videoThumbnail'
import { getImageAspectRatio } from '@/lib/imageAspectRatio'
import { getVideoAspectRatio } from '@/lib/videoThumbnail'
import ConfirmDialog from './ConfirmDialog'
import SortableItem from './SortableItem'
import { useReorderableItems } from './useReorderableItems'

export type DestacadoItem = { id: string; titulo: string; etiqueta: string; cliente: string; descripcion: string | null; media_url: string; media_tipo: 'imagen' | 'video'; aspect_ratio: string; orden: number }
type Payload = Omit<DestacadoItem, 'id' | 'orden'>; type Props = { items: DestacadoItem[]; onAdd: (item: Payload) => Promise<void>; onUpdate: (id: string, item: Payload) => Promise<void>; onDelete: (id: string) => Promise<void> }; const emptyForm: Payload = { titulo: '', etiqueta: '', cliente: '', descripcion: null, media_url: '', media_tipo: 'imagen', aspect_ratio: '1' }

export default function DestacadosList({ items, onAdd, onUpdate, onDelete }: Props) {
  const { orderedItems, sensors, handleDragEnd, reorderError } = useReorderableItems(items, '/api/admin/destacados/reorder'); const [editingId, setEditingId] = useState<string | null>(null); const [editForm, setEditForm] = useState<Payload>(emptyForm); const [addForm, setAddForm] = useState<Payload>(emptyForm); const [pendingDelete, setPendingDelete] = useState<DestacadoItem | null>(null); const [videoThumbnails, setVideoThumbnails] = useState<Record<string, string>>({}); const [uploading, setUploading] = useState(false); const [busy, setBusy] = useState(false); const [busyAction, setBusyAction] = useState<'add' | 'edit' | 'delete' | null>(null); const [error, setError] = useState(''); const thumbnailUrls = useRef<Record<string, string>>({}); const setForm = setAddForm
  useEffect(() => { let cancelled = false; async function load() { for (const item of items.filter((entry) => entry.media_tipo === 'video')) { if (thumbnailUrls.current[item.id] === item.media_url) continue; thumbnailUrls.current[item.id] = item.media_url; const thumbnail = await generateVideoThumbnail(item.media_url); if (!cancelled && thumbnail) setVideoThumbnails((current) => ({ ...current, [item.id]: thumbnail })) } }; void load(); return () => { cancelled = true } }, [items])
  function startEditing(item: DestacadoItem) { setEditingId(item.id); setEditForm({ titulo: item.titulo, etiqueta: item.etiqueta, cliente: item.cliente, descripcion: item.descripcion, media_url: item.media_url, media_tipo: item.media_tipo, aspect_ratio: item.aspect_ratio || '1' }) }
  async function upload(file: File, setForm: (value: Payload) => void, current: Payload) { setUploading(true); setError(''); try { const ratio = file.type.startsWith('video/') ? await getVideoAspectRatio(file) : await getImageAspectRatio(file); const body = new FormData(); body.append('file', file); body.append('carpeta', 'destacados'); const response = await fetch('/api/admin/upload', { method: 'POST', body }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo subir'); setForm({ ...current, media_url: data.url, media_tipo: data.tipo, aspect_ratio: ratio }) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo subir') } finally { setUploading(false) } }
  async function submit(event: React.FormEvent<HTMLFormElement>, editing: boolean) { event.preventDefault(); const form = editing ? editForm : addForm; if (!form.media_url) { setError('Sube un archivo primero'); return }; setBusy(true); setBusyAction(editing ? 'edit' : 'add'); try { if (editing && editingId) { await onUpdate(editingId, form); setEditingId(null) } else { await onAdd(form); setAddForm(emptyForm) } } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar') } finally { setBusy(false); setBusyAction(null) } }
  async function remove() { if (!pendingDelete) return; setBusy(true); setBusyAction('delete'); try { await onDelete(pendingDelete.id); setPendingDelete(null) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo eliminar') } finally { setBusy(false); setBusyAction(null) } }
  function fields(form: Payload, setForm: (value: Payload) => void) { return <><input value={form.titulo} onChange={(e) => setForm({ ...form, titulo: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2" placeholder="Título" required /><input value={form.etiqueta} onChange={(e) => setForm({ ...form, etiqueta: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2" placeholder="Etiqueta" required /><input value={form.cliente} onChange={(e) => setForm({ ...form, cliente: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2" placeholder="Cliente" required /><textarea value={form.descripcion ?? ''} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} className="min-h-24 rounded-xl border border-slate-300 px-3 py-2" placeholder="Descripción" rows={4} /><label className="inline-flex min-w-[8.5rem] cursor-pointer items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm">{uploading && <Loader2 className="h-4 w-4 animate-spin" />}{uploading ? 'Subiendo...' : 'Subir archivo'}<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4" className="sr-only" disabled={uploading} onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file, setForm, form) }} /></label></> }
  function preview(item: DestacadoItem) { const src = item.media_tipo === 'imagen' ? item.media_url : videoThumbnails[item.id]; return <div className="h-14 w-20 shrink-0 overflow-hidden rounded-xl bg-slate-100">{src ? <img src={src} alt={item.titulo} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-violet-600"><Video className="h-6 w-6" /></div>}</div> }
  return <section><h2 className="mb-4 font-serif text-xl italic text-slate-900">Trabajos recientes (destacados)</h2><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}><SortableContext items={orderedItems.map((item) => item.id)} strategy={rectSortingStrategy}><div className="grid min-w-0 gap-3">{orderedItems.map((item) => <SortableItem key={item.id} id={item.id}>{editingId === item.id ? <form onSubmit={(event) => void submit(event, true)} className="grid gap-3 rounded-2xl border border-violet-200 bg-violet-50/40 p-4">{fields(editForm, setEditForm)}<div className="flex gap-2"><button disabled={busy} className="inline-flex min-w-[6.5rem] items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">{busyAction === 'edit' && <Loader2 className="h-4 w-4 animate-spin" />}{busyAction === 'edit' ? 'Guardando...' : 'Guardar'}</button><button type="button" onClick={() => setEditingId(null)} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm">Cancelar</button></div></form> : <div className="flex min-w-0 items-center gap-3 rounded-2xl border border-slate-200 p-4">{preview(item)}<div className="min-w-0 flex-1 break-words"><p className="break-words font-semibold">{item.titulo}</p><p className="break-words text-sm text-slate-500">{item.etiqueta} · {item.cliente}</p></div><button type="button" onClick={() => startEditing(item)} className="rounded-lg p-2 text-slate-500"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => setPendingDelete(item)} disabled={busy} className="rounded-lg p-2 text-slate-500"><Trash2 className="h-4 w-4" /></button></div>}</SortableItem>)}</div></SortableContext></DndContext><form onSubmit={(event) => void submit(event, false)} className="mt-4 grid gap-3 rounded-2xl border border-dashed border-slate-300 p-4">{fields(addForm, setForm)}<button disabled={busy} className="inline-flex min-w-[6.5rem] items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">{busyAction === 'add' && <Loader2 className="h-4 w-4 animate-spin" />}{busyAction === 'add' ? 'Agregando...' : 'Agregar'}</button></form>{(error || reorderError) && <p role="alert" className="mt-3 text-sm text-red-600">{error || reorderError}</p>}<ConfirmDialog isOpen={pendingDelete !== null} title={pendingDelete ? `¿Eliminar '${pendingDelete.titulo}'?` : '¿Eliminar este ítem?'} message="Esta acción no se puede deshacer." onConfirm={remove} onCancel={() => setPendingDelete(null)} /></section>
}
