'use client'

import { useState } from 'react'
import { DndContext, closestCenter } from '@dnd-kit/core'
import { rectSortingStrategy, SortableContext } from '@dnd-kit/sortable'
import { Loader2, Pencil, Trash2 } from 'lucide-react'
import ConfirmDialog from './ConfirmDialog'
import SortableItem from './SortableItem'
import { useReorderableItems } from './useReorderableItems'

export type FormacionSobreMiItem = { id: string; institucion: string; programa: string; visible_por_defecto: boolean; orden: number }
type Payload = Omit<FormacionSobreMiItem, 'id' | 'orden'>; type Props = { items: FormacionSobreMiItem[]; onAdd: (item: Payload) => Promise<void>; onUpdate: (id: string, item: Payload) => Promise<void>; onDelete: (id: string) => Promise<void> }; const emptyForm: Payload = { institucion: '', programa: '', visible_por_defecto: true }

export default function FormacionSobreMiList({ items, onAdd, onUpdate, onDelete }: Props) {
  const { orderedItems, sensors, handleDragEnd, reorderError } = useReorderableItems(items, '/api/admin/formacion-sobre-mi/reorder'); const [editingId, setEditingId] = useState<string | null>(null); const [editForm, setEditForm] = useState<Payload>(emptyForm); const [addForm, setAddForm] = useState<Payload>(emptyForm); const [pendingDelete, setPendingDelete] = useState<FormacionSobreMiItem | null>(null); const [busy, setBusy] = useState(false); const [busyAction, setBusyAction] = useState<'add' | 'edit' | 'delete' | null>(null); const [error, setError] = useState('')
  function fields(form: Payload, setForm: (value: Payload) => void) { return <><input value={form.institucion} onChange={(e) => setForm({ ...form, institucion: e.target.value })} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2" placeholder="Institución" required /><input value={form.programa} onChange={(e) => setForm({ ...form, programa: e.target.value })} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2" placeholder="Programa" required /><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={form.visible_por_defecto} onChange={(e) => setForm({ ...form, visible_por_defecto: e.target.checked })} />Visible siempre</label></> }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const action = editingId ? 'edit' : 'add'; setBusy(true); setBusyAction(action); try { if (editingId) { await onUpdate(editingId, editForm); setEditingId(null) } else { await onAdd(addForm); setAddForm(emptyForm) } } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar') } finally { setBusy(false); setBusyAction(null) } }
  async function remove() { if (!pendingDelete) return; setBusy(true); setBusyAction('delete'); try { await onDelete(pendingDelete.id); setPendingDelete(null) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo eliminar') } finally { setBusy(false); setBusyAction(null) } }
  return <section><h2 className="mb-4 font-serif text-xl italic text-slate-900">Formación (Sobre mí)</h2><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}><SortableContext items={orderedItems.map((item) => item.id)} strategy={rectSortingStrategy}><div className="grid min-w-0 gap-3">{orderedItems.map((item) => <SortableItem key={item.id} id={item.id}>{editingId === item.id ? <form onSubmit={submit} className="grid gap-3 rounded-2xl border border-violet-200 bg-violet-50/40 p-4">{fields(editForm, setEditForm)}<div className="flex gap-2"><button disabled={busy} className="inline-flex min-w-[6.5rem] items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">{busyAction === 'edit' && <Loader2 className="h-4 w-4 animate-spin" />}{busyAction === 'edit' ? 'Guardando...' : 'Guardar'}</button><button type="button" onClick={() => setEditingId(null)} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm">Cancelar</button></div></form> : <div className="flex min-w-0 items-start gap-3 rounded-2xl border border-slate-200 p-4"><div className="min-w-0 flex-1 break-words"><p className="break-words font-semibold">{item.institucion}</p><p className="break-words text-sm text-slate-500">{item.programa}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-xs font-semibold ${item.visible_por_defecto ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{item.visible_por_defecto ? 'Visible' : 'Oculta'}</span><button type="button" onClick={() => { setEditingId(item.id); setEditForm({ institucion: item.institucion, programa: item.programa, visible_por_defecto: item.visible_por_defecto }) }} className="rounded-lg p-2 text-slate-500"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => setPendingDelete(item)} disabled={busy} className="rounded-lg p-2 text-slate-500"><Trash2 className="h-4 w-4" /></button></div>}</SortableItem>)}</div></SortableContext></DndContext><form onSubmit={submit} className="mt-4 grid gap-3 rounded-2xl border border-dashed border-slate-300 p-4">{fields(addForm, setAddForm)}<button disabled={busy} className="inline-flex min-w-[6.5rem] items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">{busyAction === 'add' && <Loader2 className="h-4 w-4 animate-spin" />}{busyAction === 'add' ? 'Agregando...' : 'Agregar'}</button></form>{(error || reorderError) && <p role="alert" className="mt-3 text-sm text-red-600">{error || reorderError}</p>}<ConfirmDialog isOpen={pendingDelete !== null} title={pendingDelete ? `¿Eliminar '${pendingDelete.institucion}'?` : '¿Eliminar este ítem?'} message="Esta acción no se puede deshacer." onConfirm={remove} onCancel={() => setPendingDelete(null)} /></section>
}
