'use client'

import { useEffect, useState } from 'react'
import { Loader2, Trash2, Video } from 'lucide-react'
import { generateVideoThumbnail } from '@/lib/videoThumbnail'
import type { ProyectoMedia, ProyectoTag } from './ProyectoCard'
import TagInput from './TagInput'

export type ProyectoFormData = { titulo: string; categoria: 'empresa' | 'independiente'; cliente_o_rol: string; descripcion_corta: string; link_url: string | null }
type Props = { mode: 'create' | 'edit'; form: ProyectoFormData; setForm: (value: ProyectoFormData) => void; tags: ProyectoTag[]; reorderUrl?: string; draftTags?: string[]; onDraftTagAdd?: (name: string) => void; onDraftTagRemove?: (index: number) => void; onTagDelete?: (tag: ProyectoTag) => void; media: ProyectoMedia[]; selectedFiles?: File[]; onSelectedFilesChange?: (files: File[]) => void; onUploadMedia?: (file: File) => void; onMediaDelete?: (media: ProyectoMedia) => void; uploading?: boolean; busy: boolean; error?: string }

export default function ProyectoForm({ mode, form, setForm, tags, reorderUrl, draftTags = [], onDraftTagAdd, onDraftTagRemove, onTagDelete, media, selectedFiles = [], onSelectedFilesChange, onUploadMedia, onMediaDelete, uploading = false, busy, error }: Props) {
  const [tagName, setTagName] = useState('')
  const [thumbnails, setThumbnails] = useState<Record<string, string>>({})
  useEffect(() => { let cancelled = false; async function load() { for (const item of media.filter((entry) => entry.tipo === 'video' && !entry.thumbnail_url)) { const thumbnail = await generateVideoThumbnail(item.url); if (!cancelled && thumbnail) setThumbnails((current) => ({ ...current, [item.id]: thumbnail })) } }; void load(); return () => { cancelled = true } }, [media])
  function addDraftTag() { const name = tagName.trim(); if (!name) return; onDraftTagAdd?.(name); setTagName('') }
  function mediaThumb(item: ProyectoMedia) { const src = item.tipo === 'imagen' ? item.url : item.thumbnail_url || thumbnails[item.id]; return <div key={item.id} className="relative h-16 w-20 overflow-hidden rounded-xl bg-slate-100">{src ? <img src={src} alt="Media del proyecto" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-violet-600"><Video className="h-6 w-6" /></div>}{mode === 'edit' && <button type="button" title="Eliminar archivo" onClick={() => onMediaDelete?.(item)} disabled={busy || media.length <= 1} className="absolute right-1 top-1 rounded-full bg-white/90 p-1 text-red-600 disabled:cursor-not-allowed disabled:opacity-40"><Trash2 className="h-3 w-3" /></button>}</div> }
  return <div className="grid gap-4">
    <input value={form.titulo} onChange={(e) => setForm({ ...form, titulo: e.target.value })} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2" placeholder="Título" required />
    <div className="flex gap-2"><button type="button" onClick={() => setForm({ ...form, categoria: 'empresa' })} className={`rounded-xl px-3 py-2 text-sm ${form.categoria === 'empresa' ? 'bg-violet-600 text-white' : 'border border-slate-300'}`}>Empresa</button><button type="button" onClick={() => setForm({ ...form, categoria: 'independiente' })} className={`rounded-xl px-3 py-2 text-sm ${form.categoria === 'independiente' ? 'bg-violet-600 text-white' : 'border border-slate-300'}`}>Independiente</button></div>
    <input value={form.cliente_o_rol} onChange={(e) => setForm({ ...form, cliente_o_rol: e.target.value })} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2" placeholder="Cliente o rol" required />
    <textarea value={form.descripcion_corta} onChange={(e) => setForm({ ...form, descripcion_corta: e.target.value })} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2" placeholder="Descripción corta" rows={3} required />
    <input type="url" value={form.link_url ?? ''} onChange={(e) => setForm({ ...form, link_url: e.target.value || null })} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2" placeholder="https://... (opcional)" />
    <div>{mode === 'edit' ? <TagInput items={tags} onAdd={async (name) => { onDraftTagAdd?.(name) }} onRemove={async (id) => { const tag = tags.find((item) => item.id === id); if (tag) onTagDelete?.(tag) }} label="Tags" reorderUrl={reorderUrl} /> : <><h3 className="mb-2 font-semibold text-slate-800">Tags</h3><div className="mb-2 flex flex-wrap gap-2">{draftTags.map((tag, index) => <span key={`${tag}-${index}`} className="inline-flex items-center gap-2 rounded-full bg-[#F4EEFC] px-3 py-1.5 text-sm text-[#6B4FB0]">{tag}<button type="button" onClick={() => onDraftTagRemove?.(index)} aria-label={`Eliminar ${tag}`} className="text-current/60">x</button></span>)}</div><div className="flex gap-2"><input value={tagName} onChange={(e) => setTagName(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); addDraftTag() } }} className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2" placeholder="Agregar tag" /><button type="button" onClick={addDraftTag} disabled={!tagName.trim() || busy} className="rounded-xl bg-violet-100 px-3 text-violet-700 disabled:opacity-40">+</button></div></>}</div>
     <div><div className="mb-2 flex items-center justify-between gap-2"><h3 className="font-semibold text-slate-800">Galería</h3>{mode === 'edit' && media.length >= 10 ? <span className="text-xs text-slate-500">Máximo alcanzado (10/10)</span> : <label className="inline-flex min-w-[9.5rem] cursor-pointer items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm">{uploading && <Loader2 className="h-4 w-4 animate-spin" />}{uploading ? 'Subiendo...' : '＋ Agregar archivo'}<input type="file" multiple={mode === 'create'} accept="image/jpeg,image/png,image/webp,video/mp4" className="sr-only" disabled={busy || uploading || (mode === 'edit' && media.length >= 10)} onChange={(e) => { const files = Array.from(e.target.files ?? []); if (mode === 'create') onSelectedFilesChange?.([...selectedFiles, ...files].slice(0, 10)); else files.forEach((file) => onUploadMedia?.(file)) }} /></label>}</div><div className="flex flex-wrap gap-2">{media.map(mediaThumb)}{mode === 'create' && selectedFiles.map((file, index) => <div key={`${file.name}-${index}`} className="relative flex h-16 min-w-20 items-center justify-center rounded-xl bg-slate-100 px-2 text-xs text-slate-600"><span className="max-w-20 break-words text-center">{file.type === 'video/mp4' ? 'Video' : file.name}</span><button type="button" onClick={() => onSelectedFilesChange?.(selectedFiles.filter((_, fileIndex) => fileIndex !== index))} className="absolute right-1 top-1 rounded-full bg-white/90 p-1 text-red-600"><Trash2 className="h-3 w-3" /></button></div>)}</div>{mode === 'create' && selectedFiles.length >= 10 && <p className="mt-1 text-xs text-slate-500">Máximo alcanzado (10/10)</p>}</div>
    {error && <p role="alert" className="text-sm text-red-600">{error}</p>}
  </div>
}
