'use client'

import { useState } from 'react'
import { ChevronDown, ChevronUp, Loader2, Trash2, Video } from 'lucide-react'
import ConfirmDialog from './ConfirmDialog'
import ProyectoForm, { ProyectoFormData } from './ProyectoForm'

export type ProyectoTag = { id: string; proyecto_id: string; nombre: string; orden: number }
export type ProyectoMedia = { id: string; proyecto_id: string; tipo: 'imagen' | 'video'; url: string; thumbnail_url: string | null; orden: number }
export type ProyectoItem = { id: string; titulo: string; categoria: 'empresa' | 'independiente'; cliente_o_rol: string; descripcion_corta: string; link_url: string | null; orden: number; proyecto_tags: ProyectoTag[]; proyecto_media: ProyectoMedia[] }
type Props = { item: ProyectoItem; onUpdate: (id: string, data: ProyectoFormData) => Promise<void>; onDelete: (id: string) => Promise<void>; onTagAdd: (id: string, tag: ProyectoTag) => void; onTagDelete: (id: string, tagId: string) => Promise<void>; onMediaAdd: (id: string, media: ProyectoMedia) => void; onMediaDelete: (id: string, mediaId: string) => Promise<void> }

export default function ProyectoCard({ item, onUpdate, onDelete, onTagAdd, onTagDelete, onMediaAdd, onMediaDelete }: Props) {
  const [expanded, setExpanded] = useState(false)
  const [form, setForm] = useState<ProyectoFormData>({ titulo: item.titulo, categoria: item.categoria, cliente_o_rol: item.cliente_o_rol, descripcion_corta: item.descripcion_corta, link_url: item.link_url })
  const [pendingMedia, setPendingMedia] = useState<ProyectoMedia | null>(null)
  const [pendingDelete, setPendingDelete] = useState(false)
  const [busy, setBusy] = useState(false)
  const [saving, setSaving] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [error, setError] = useState('')

  async function save() { setBusy(true); setSaving(true); setError(''); try { await onUpdate(item.id, form) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar') } finally { setBusy(false); setSaving(false) } }
  async function removeTag(tag: ProyectoTag) { setBusy(true); try { await onTagDelete(item.id, tag.id) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo eliminar el tag') } finally { setBusy(false) } }
  async function uploadMedia(file: File) { setBusy(true); setUploading(true); setError(''); try { const formData = new FormData(); formData.append('file', file); formData.append('carpeta', `proyectos/${item.id}`); const upload = await fetch('/api/admin/upload', { method: 'POST', body: formData }); const uploaded = await upload.json(); if (!upload.ok) throw new Error(uploaded.error || 'No se pudo subir el archivo'); const response = await fetch(`/api/admin/proyectos/${item.id}/media`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: uploaded.url, tipo: uploaded.tipo }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo asociar el archivo'); onMediaAdd(item.id, data) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo agregar el archivo') } finally { setBusy(false); setUploading(false) } }
  async function removeMedia() { if (!pendingMedia) return; setBusy(true); try { await onMediaDelete(item.id, pendingMedia.id); setPendingMedia(null) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo eliminar el archivo') } finally { setBusy(false) } }
  async function removeProject() { setBusy(true); try { await onDelete(item.id) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo eliminar el proyecto') } finally { setBusy(false); setPendingDelete(false) } }

  const firstMedia = item.proyecto_media[0]
  return <article className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex min-w-0 items-center gap-3"><div className="h-14 w-20 shrink-0 overflow-hidden rounded-xl bg-slate-100">{firstMedia ? firstMedia.tipo === 'imagen' ? <img src={firstMedia.url} alt={item.titulo} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-violet-600"><Video className="h-6 w-6" /></div> : <div className="flex h-full items-center justify-center text-slate-400">Sin media</div>}</div><div className="min-w-0 flex-1 break-words [overflow-wrap:anywhere]"><p className="break-words font-semibold text-slate-900 [overflow-wrap:anywhere]">{item.titulo}</p><p className="break-words text-sm text-slate-500 [overflow-wrap:anywhere]">{item.cliente_o_rol} · {item.categoria}</p><p className="text-xs text-slate-400">{item.proyecto_media.length} archivos · {item.proyecto_tags.length} tags</p></div><button type="button" onClick={() => setExpanded(!expanded)} aria-label={expanded ? 'Colapsar proyecto' : 'Expandir proyecto'} className="shrink-0 rounded-lg p-2 text-slate-500 hover:bg-violet-50 hover:text-violet-600">{expanded ? <ChevronUp /> : <ChevronDown />}</button></div>
     {expanded && <div className="mt-4 grid gap-4 border-t border-slate-100 pt-4"><ProyectoForm mode="edit" form={form} setForm={setForm} tags={item.proyecto_tags} reorderUrl={`/api/admin/proyectos/${item.id}/tags/reorder`} media={item.proyecto_media} onDraftTagAdd={async (name) => { if (!name) return; setBusy(true); try { const response = await fetch(`/api/admin/proyectos/${item.id}/tags`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nombre: name }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo agregar el tag'); onTagAdd(item.id, data) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo agregar el tag') } finally { setBusy(false) } }} onTagDelete={(tag) => void removeTag(tag)} onUploadMedia={(file) => void uploadMedia(file)} onMediaDelete={setPendingMedia} uploading={uploading} busy={busy} error={error} /><button type="button" onClick={save} disabled={busy} className="inline-flex min-w-[9.5rem] items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{saving ? 'Guardando...' : 'Guardar cambios'}</button><button type="button" onClick={() => setPendingDelete(true)} disabled={busy} className="flex w-fit items-center gap-2 rounded-xl bg-red-600 px-4 py-2 text-sm font-semibold text-white hover:bg-red-700 disabled:opacity-50"><Trash2 className="h-4 w-4" />Eliminar proyecto</button></div>}
    <ConfirmDialog isOpen={pendingMedia !== null} title="¿Eliminar este archivo?" message={item.proyecto_media.length <= 1 ? 'El proyecto debe conservar al menos un archivo.' : 'Esta acción no se puede deshacer.'} onConfirm={removeMedia} onCancel={() => setPendingMedia(null)} /><ConfirmDialog isOpen={pendingDelete} title={`¿Eliminar '${item.titulo}'?`} message="Se eliminarán también sus tags y archivos." onConfirm={removeProject} onCancel={() => setPendingDelete(false)} />
  </article>
}
