'use client'

import { useState } from 'react'
import { Loader2 } from 'lucide-react'
import { DndContext, closestCenter } from '@dnd-kit/core'
import { rectSortingStrategy, SortableContext } from '@dnd-kit/sortable'
import ProyectoCard, { ProyectoItem, ProyectoMedia, ProyectoTag } from './ProyectoCard'
import ProyectoForm, { ProyectoFormData } from './ProyectoForm'
import SortableItem from './SortableItem'
import { useReorderableItems } from './useReorderableItems'
export type { ProyectoItem, ProyectoMedia, ProyectoTag }
type Props = { items: ProyectoItem[]; onAdd: (item: ProyectoItem) => void; onUpdate: (id: string, data: ProyectoFormData) => Promise<void>; onDelete: (id: string) => Promise<void>; onTagAdd: (id: string, tag: ProyectoTag) => void; onTagDelete: (id: string, tagId: string) => Promise<void>; onMediaAdd: (id: string, media: ProyectoMedia) => void; onMediaDelete: (id: string, mediaId: string) => Promise<void> }
const initialForm: ProyectoFormData = { titulo: '', categoria: 'empresa', cliente_o_rol: '', descripcion_corta: '', link_url: null }

export default function ProyectosList({ items, onAdd, onUpdate, onDelete, onTagAdd, onTagDelete, onMediaAdd, onMediaDelete }: Props) {
  const company = useReorderableItems(items.filter((item) => item.categoria === 'empresa'), '/api/admin/proyectos/reorder'); const independent = useReorderableItems(items.filter((item) => item.categoria === 'independiente'), '/api/admin/proyectos/reorder')
  const [form, setForm] = useState<ProyectoFormData>(initialForm); const [draftTags, setDraftTags] = useState<string[]>([]); const [files, setFiles] = useState<File[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  async function createProject(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!files.length) { setError('Sube al menos un archivo antes de crear el proyecto'); return }; setSaving(true); setError(''); try { const response = await fetch('/api/admin/proyectos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const project = await response.json(); if (!response.ok) throw new Error(project.error || 'No se pudo crear el proyecto'); const media: ProyectoMedia[] = []; for (const file of files) { const body = new FormData(); body.append('file', file); body.append('carpeta', `proyectos/${project.id}`); const upload = await fetch('/api/admin/upload', { method: 'POST', body }); const uploaded = await upload.json(); if (!upload.ok) throw new Error(uploaded.error || 'No se pudo subir el archivo'); const mediaResponse = await fetch(`/api/admin/proyectos/${project.id}/media`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: uploaded.url, tipo: uploaded.tipo }) }); const mediaItem = await mediaResponse.json(); if (!mediaResponse.ok) throw new Error(mediaItem.error || 'No se pudo asociar el archivo'); media.push(mediaItem) }; const tags: ProyectoTag[] = []; for (const nombre of draftTags) { const tagResponse = await fetch(`/api/admin/proyectos/${project.id}/tags`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nombre }) }); const tag = await tagResponse.json(); if (!tagResponse.ok) throw new Error(tag.error || 'No se pudo asociar el tag'); tags.push(tag) }; onAdd({ ...project, proyecto_media: media, proyecto_tags: tags }); setForm(initialForm); setDraftTags([]); setFiles([]) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo crear el proyecto') } finally { setSaving(false) } }
  function group(result: ReturnType<typeof useReorderableItems<ProyectoItem>>, title: string) { return <section><h3 className="mb-3 font-serif text-lg italic text-slate-900">{title}</h3><DndContext sensors={result.sensors} collisionDetection={closestCenter} onDragEnd={result.handleDragEnd}><SortableContext items={result.orderedItems.map((item) => item.id)} strategy={rectSortingStrategy}><div className="grid gap-3">{result.orderedItems.map((item) => <SortableItem key={item.id} id={item.id}><ProyectoCard item={item} onUpdate={onUpdate} onDelete={onDelete} onTagAdd={onTagAdd} onTagDelete={onTagDelete} onMediaAdd={onMediaAdd} onMediaDelete={onMediaDelete} /></SortableItem>)}</div></SortableContext></DndContext>{result.reorderError && <p role="alert" className="mt-2 text-sm text-red-600">{result.reorderError}</p>}</section> }
  return <section><h2 className="mb-4 font-serif text-xl italic text-slate-900">Proyectos</h2><form onSubmit={(event) => void createProject(event)} className="mb-6 rounded-2xl border border-dashed border-slate-300 p-4"><h3 className="mb-4 font-semibold text-slate-800">Nuevo proyecto</h3><ProyectoForm mode="create" form={form} setForm={setForm} tags={[]} draftTags={draftTags} onDraftTagAdd={(tag) => { if (tag && !draftTags.includes(tag)) setDraftTags([...draftTags, tag]) }} onDraftTagRemove={(index) => setDraftTags(draftTags.filter((_, tagIndex) => tagIndex !== index))} media={[]} selectedFiles={files} onSelectedFilesChange={setFiles} busy={saving} error={error} /><button disabled={saving} className="mt-4 inline-flex min-w-[8.5rem] items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{saving ? 'Creando...' : 'Crear proyecto'}</button></form>{group(company, 'Proyectos para empresas')}{group(independent, 'Proyectos independientes')}</section>
}
