'use client'

import { useState } from 'react'
import { DndContext, closestCenter } from '@dnd-kit/core'
import { rectSortingStrategy, SortableContext } from '@dnd-kit/sortable'
import { Loader2, Pencil, Trash2 } from 'lucide-react'
import ConfirmDialog from './ConfirmDialog'
import SortableItem from './SortableItem'
import { useReorderableItems } from './useReorderableItems'

export type TrayectoriaItem = { id: string; empresa_o_contexto: string; rol: string; fecha_inicio: string; fecha_fin: string | null; color_punto: string; orden: number }
type Payload = Omit<TrayectoriaItem, 'id' | 'orden' | 'color_punto'>
type Props = { items: TrayectoriaItem[]; onAdd: (item: Payload) => Promise<void>; onUpdate: (id: string, item: Payload) => Promise<void>; onDelete: (id: string) => Promise<void> }
const emptyForm: Payload = { empresa_o_contexto: '', rol: '', fecha_inicio: '', fecha_fin: '' }

export default function TrayectoriaList({ items, onAdd, onUpdate, onDelete }: Props) {
  const { orderedItems, sensors, handleDragEnd, reorderError } = useReorderableItems(items, '/api/admin/trayectoria/reorder')
  const [editingId, setEditingId] = useState<string | null>(null); const [editForm, setEditForm] = useState<Payload>(emptyForm); const [addForm, setAddForm] = useState<Payload>(emptyForm); const [pendingDelete, setPendingDelete] = useState<TrayectoriaItem | null>(null); const [busy, setBusy] = useState(false); const [busyAction, setBusyAction] = useState<'add' | 'edit' | 'delete' | null>(null); const [error, setError] = useState('')
  function startEditing(item: TrayectoriaItem) { setEditingId(item.id); setEditForm({ empresa_o_contexto: item.empresa_o_contexto, rol: item.rol, fecha_inicio: item.fecha_inicio, fecha_fin: item.fecha_fin ?? '' }) }
  async function submitAdd(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setBusyAction('add'); try { await onAdd({ ...addForm, fecha_fin: addForm.fecha_fin || null }); setAddForm(emptyForm) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo agregar') } finally { setBusy(false); setBusyAction(null) } }
  async function submitEdit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editingId) return; setBusy(true); setBusyAction('edit'); try { await onUpdate(editingId, { ...editForm, fecha_fin: editForm.fecha_fin || null }); setEditingId(null) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo actualizar') } finally { setBusy(false); setBusyAction(null) } }
  async function remove() { if (!pendingDelete) return; setBusy(true); setBusyAction('delete'); try { await onDelete(pendingDelete.id); setPendingDelete(null) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo eliminar') } finally { setBusy(false); setBusyAction(null) } }
  function fields(form: Payload, setForm: (value: Payload) => void) { const current = !form.fecha_fin; return <><input value={form.empresa_o_contexto} onChange={(e) => setForm({ ...form, empresa_o_contexto: e.target.value })} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2" placeholder="Empresa o contexto" required /><input value={form.rol} onChange={(e) => setForm({ ...form, rol: e.target.value })} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2" placeholder="Rol" required /><input value={form.fecha_inicio} onChange={(e) => setForm({ ...form, fecha_inicio: e.target.value })} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2" placeholder="Fecha de inicio" required /><div className="grid gap-2"><input value={form.fecha_fin ?? ''} onChange={(e) => setForm({ ...form, fecha_fin: e.target.value })} disabled={current} className="min-w-0 rounded-xl border border-slate-300 px-3 py-2 disabled:bg-slate-100" placeholder="Fecha de fin" /><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={current} onChange={(e) => setForm({ ...form, fecha_fin: e.target.checked ? '' : ' ' })} />Actualmente aquí</label></div></> }
  return <section><h2 className="mb-4 font-serif text-xl italic text-slate-900">Trayectoria</h2><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}><SortableContext items={orderedItems.map((item) => item.id)} strategy={rectSortingStrategy}><div className="grid min-w-0 gap-3">{orderedItems.map((item) => <SortableItem key={item.id} id={item.id}>{editingId === item.id ? <form onSubmit={submitEdit} className="grid gap-3 rounded-2xl border border-violet-200 bg-violet-50/40 p-4">{fields(editForm, setEditForm)}<div className="flex gap-2"><button disabled={busy} className="inline-flex min-w-[6.5rem] items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">{busyAction === 'edit' && <Loader2 className="h-4 w-4 animate-spin" />}{busyAction === 'edit' ? 'Guardando...' : 'Guardar'}</button><button type="button" onClick={() => setEditingId(null)} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm">Cancelar</button></div></form> : <div className="flex min-w-0 max-w-full items-start gap-3 overflow-hidden rounded-2xl border border-slate-200 p-4"><span className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full" style={{ backgroundColor: item.color_punto }} /><div className="min-w-0 flex-1 break-words"><p className="break-words font-semibold">{item.empresa_o_contexto}</p><p className="break-words text-sm text-slate-500">{item.rol} · {item.fecha_inicio}—{item.fecha_fin || 'Presente'}</p></div><div className="flex shrink-0 gap-1"><button type="button" onClick={() => startEditing(item)} className="rounded-lg p-2 text-slate-500"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => setPendingDelete(item)} disabled={busy} className="rounded-lg p-2 text-slate-500"><Trash2 className="h-4 w-4" /></button></div></div>}</SortableItem>)}</div></SortableContext></DndContext><form onSubmit={submitAdd} className="mt-4 grid gap-3 rounded-2xl border border-dashed border-slate-300 p-4">{fields(addForm, setAddForm)}<button disabled={busy} className="inline-flex min-w-[6.5rem] items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">{busyAction === 'add' && <Loader2 className="h-4 w-4 animate-spin" />}{busyAction === 'add' ? 'Agregando...' : 'Agregar'}</button></form>{(error || reorderError) && <p role="alert" className="mt-3 text-sm text-red-600">{error || reorderError}</p>}<ConfirmDialog isOpen={pendingDelete !== null} title={pendingDelete ? `¿Eliminar '${pendingDelete.empresa_o_contexto}'?` : '¿Eliminar este ítem?'} message="Esta acción no se puede deshacer." onConfirm={remove} onCancel={() => setPendingDelete(null)} /></section>
}
