import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { requireAdminAuth } from '@/lib/requireAuth'

type Body = { titulo?: unknown; institucion?: unknown; fecha?: unknown; descripcion?: unknown; imagen_url?: unknown; aspect_ratio?: unknown }
function unauthorizedResponse() { return NextResponse.json({ error: 'No autorizado' }, { status: 401 }) }
function fields(body: Body) { return { titulo: typeof body.titulo === 'string' ? body.titulo.trim() : '', institucion: typeof body.institucion === 'string' ? body.institucion.trim() : '', fecha: typeof body.fecha === 'string' ? body.fecha.trim() : '', descripcion: typeof body.descripcion === 'string' ? body.descripcion.trim() : '', imagen_url: typeof body.imagen_url === 'string' ? body.imagen_url.trim() : '', aspect_ratio: typeof body.aspect_ratio === 'string' && body.aspect_ratio.trim() ? body.aspect_ratio.trim() : '1' } }
function storagePath(url: unknown) { const marker = '/storage/v1/object/public/portfolio-media/'; return typeof url === 'string' && url.includes(marker) ? decodeURIComponent(url.split(marker)[1]) : null }
async function removeFile(client: ReturnType<typeof createAdminClient>, url: unknown, context: string) { const path = storagePath(url); if (!path) return; console.log(`Eliminando imagen de certificación (${context}) de Storage:`, path); const { error } = await client.storage.from('portfolio-media').remove([path]); if (error) console.error('No se pudo eliminar la imagen de certificación:', error) }
async function nextOrder() { const { data, error } = await createAdminClient().from('certificaciones').select('orden').order('orden', { ascending: false }).limit(1).maybeSingle(); if (error) throw error; return data ? data.orden + 1 : 0 }

export async function GET() { try { await requireAdminAuth() } catch { return unauthorizedResponse() }; const { data, error } = await createAdminClient().from('certificaciones').select('*').order('orden', { ascending: true }); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json(data, { status: 200 }) }
export async function POST(request: Request) { try { await requireAdminAuth() } catch { return unauthorizedResponse() }; try { const value = fields(await request.json()); if (!value.titulo || !value.institucion || !value.fecha || !value.descripcion || !value.imagen_url) return NextResponse.json({ error: 'Título, institución, fecha, descripción e imagen requeridos' }, { status: 400 }); const { data, error } = await createAdminClient().from('certificaciones').insert({ ...value, orden: await nextOrder() }).select().single(); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json(data, { status: 200 }) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Error desconocido' }, { status: 500 }) } }
export async function PUT(request: Request) { try { await requireAdminAuth() } catch { return unauthorizedResponse() }; try { const body = await request.json() as Body & { id?: unknown }; const id = typeof body.id === 'string' ? body.id : ''; if (!id) return NextResponse.json({ error: 'Id requerido' }, { status: 400 }); const value = fields(body); if (!value.titulo || !value.institucion || !value.fecha || !value.descripcion || !value.imagen_url) return NextResponse.json({ error: 'Título, institución, fecha, descripción e imagen requeridos' }, { status: 400 }); const client = createAdminClient(); const { data: previous, error: previousError } = await client.from('certificaciones').select('imagen_url').eq('id', id).maybeSingle(); if (previousError) return NextResponse.json({ error: previousError.message }, { status: 500 }); const { data, error } = await client.from('certificaciones').update(value).eq('id', id).select().single(); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); if (previous?.imagen_url && previous.imagen_url !== value.imagen_url) await removeFile(client, previous.imagen_url, 'reemplazo'); return NextResponse.json(data, { status: 200 }) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Error desconocido' }, { status: 500 }) } }
export async function DELETE(request: Request) { try { await requireAdminAuth() } catch { return unauthorizedResponse() }; const id = new URL(request.url).searchParams.get('id'); if (!id) return NextResponse.json({ error: 'Id requerido' }, { status: 400 }); const client = createAdminClient(); const { data } = await client.from('certificaciones').select('imagen_url').eq('id', id).maybeSingle(); if (data?.imagen_url) await removeFile(client, data.imagen_url, 'eliminación'); const { error } = await client.from('certificaciones').delete().eq('id', id); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ success: true }, { status: 200 }) }
